/**
 * LLM attribution: the assisting model is credited only when a policy was
 * actually LLM-reviewed, is sanitized, and appears in the output top line.
 */

import { describe, it, expect } from 'vitest';
import { resolveAssistModel } from '../public/utils/llm-attribution.js';
import { versionStamp, sanitizeModelLabel, APP_VERSION } from '../src/version.js';
import { convertToSrxSetCommands } from '../src/converters/srx-converter.js';
import { buildSrxXml } from '../src/converters/srx-xml-builder.js';

describe('resolveAssistModel', () => {
  const reviewed = [{ _review_status: 'llm_reviewed' }, { _review_status: 'accepted' }];
  const none = [{ _review_status: 'accepted' }, { _review_status: 'unreviewed' }];

  it('returns the model when a policy was llm_reviewed', () => {
    expect(resolveAssistModel(reviewed, { model: 'ornith:35b' })).toBe('ornith:35b');
  });

  it('returns empty when no policy was llm_reviewed (deterministic run)', () => {
    expect(resolveAssistModel(none, { model: 'ornith:35b' })).toBe('');
  });

  it('returns empty for missing/empty inputs', () => {
    expect(resolveAssistModel(undefined, { model: 'x' })).toBe('');
    expect(resolveAssistModel(reviewed, undefined)).toBe('');
  });

  it('sanitizes an unsafe model label', () => {
    expect(resolveAssistModel(reviewed, { model: 'evil\nset system' })).toBe('evilset system');
  });
});

describe('versionStamp', () => {
  it('omits the LLM part when no model', () => {
    expect(versionStamp('')).toBe(`Generated by firewallintentconverter v${APP_VERSION}`);
  });
  it('appends the LLM model when present', () => {
    expect(versionStamp('claude-opus-4-8')).toBe(`Generated by firewallintentconverter v${APP_VERSION} | LLM: claude-opus-4-8`);
  });
  it('strips control chars from the model', () => {
    expect(sanitizeModelLabel('a\tb\n')).toBe('ab');
  });
});

const baseConfig = {
  zones: [{ name: 'trust', interfaces: ['ethernet1/1'] }],
  interfaces: [{ name: 'ethernet1/1', zone: 'trust', ip: '10.0.0.1/24' }],
  security_policies: [], service_objects: [], address_objects: [],
  address_groups: [], nat_rules: [],
};

describe('LLM model in generated output', () => {
  it('set output top line includes the LLM model when provided', () => {
    const result = convertToSrxSetCommands(baseConfig, {}, null, { llmModel: 'ornith:35b' });
    expect(result.commands[0]).toBe(`# Generated by firewallintentconverter v${APP_VERSION} | LLM: ornith:35b`);
  });

  it('set output omits LLM part when not provided', () => {
    const result = convertToSrxSetCommands(baseConfig);
    expect(result.commands[0]).toBe(`# Generated by firewallintentconverter v${APP_VERSION}`);
  });

  it('XML output includes the LLM model in its version comment', () => {
    const { xml } = buildSrxXml(baseConfig, {}, null, { llmModel: 'ornith:35b' });
    expect(xml).toContain(`v${APP_VERSION} | LLM: ornith:35b`);
  });
});
