import { describe, expect, it } from 'vitest';
import { generateReportHtml } from '../public/utils/report-generator.js';

const reportInput = {
  sourceVendor: 'panos',
  sourceModel: 'PA-440',
  targetModel: 'SRX1600',
  siteName: 'branch-a',
  intermediateConfig: {
    zones: [],
    interfaces: [],
    security_policies: [],
    nat_rules: [],
    address_objects: [],
    service_objects: [],
    static_routes: [],
  },
};

describe('Mechub report branding', () => {
  it('brands the self-contained HTML migration report', () => {
    const html = generateReportHtml(reportInput);
    expect(html).toContain('class="mechub-report-mark"');
    expect(html).toContain('M18,96 L18,32 L60,74 L102,32 L102,96');
    expect(html).toContain('firewall<span class="brand-intent">intent</span>converter');
    expect(html).toContain('a mechub project');
    expect(html).toContain('#0B0D12');
    expect(html).toContain('#4DD0C8');
    expect(html).toContain('#90C641');
    expect(html).not.toContain('Generated by Firewall Intent Converter');
    expect(html).not.toMatch(/<svg[^>]+(?:href|src)=|<script/i);
  });
});
