/**
 * Version stamping: every generated output carries the tool version so an
 * artifact can be tied back to the version that produced it.
 */

import { describe, it, expect } from 'vitest';
import { convertToSrxSetCommands } from '../src/converters/srx-converter.js';
import { buildSrxXml } from '../src/converters/srx-xml-builder.js';
import { validateXmlOutput } from '../src/security/junos-output-validation.js';
import { APP_VERSION } from '../src/version.js';

const baseConfig = {
  zones: [{ name: 'trust', interfaces: ['ethernet1/1'] }],
  interfaces: [{ name: 'ethernet1/1', zone: 'trust', ip: '10.0.0.1/24' }],
  security_policies: [], service_objects: [], address_objects: [],
  address_groups: [], nat_rules: [],
};

describe('version stamping', () => {
  it('APP_VERSION is a semver string', () => {
    expect(APP_VERSION).toMatch(/^\d+\.\d+\.\d+/);
  });

  it('set output includes a version comment', () => {
    const result = convertToSrxSetCommands(baseConfig);
    expect(result.commands.some(c => c === `# Generated by firewallintentconverter v${APP_VERSION}`)).toBe(true);
  });

  it('XML output includes a version comment inside the configuration root and stays well-formed', () => {
    const { xml } = buildSrxXml(baseConfig);
    expect(xml).toContain(`firewallintentconverter v${APP_VERSION}`);
    // The comment must not break output validation (content outside root is rejected).
    expect(() => validateXmlOutput(xml)).not.toThrow();
    // And it must sit after <configuration>, not before it.
    expect(xml.indexOf('<configuration>')).toBeLessThan(xml.indexOf(`firewallintentconverter v${APP_VERSION}`));
  });
});
