// Import attribute is required for native Node ESM (the CI self-contained suites
// run these modules under `node` directly); Vite/vitest also accept it.
import pkg from '../package.json' with { type: 'json' };

/**
 * Application version — single source of truth is package.json.
 * Stamped into the UI footer, every generated output file (set + XML), and the
 * PDF report so a given artifact can be tied back to the tool version that
 * produced it.
 * @type {string}
 */
export const APP_VERSION = pkg.version;

/**
 * Restrict an LLM model label to a safe, comment-embeddable character set
 * (defence for output comments — the value originates from user settings).
 * @param {string} [model]
 * @returns {string}
 */
export function sanitizeModelLabel(model) {
  return String(model || '').replace(/[^A-Za-z0-9 ._:/@+-]/g, '').trim().slice(0, 64);
}

/**
 * Build the provenance stamp used in the top line of generated output and the
 * PDF report: the tool version, plus the assisting LLM model when one helped.
 * @param {string} [llmModel] - assisting model id, or '' / undefined for none
 * @returns {string}
 */
export function versionStamp(llmModel) {
  const base = `Generated by firewallintentconverter v${APP_VERSION}`;
  const model = sanitizeModelLabel(llmModel);
  return model ? `${base} | LLM: ${model}` : base;
}
